// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/autoscaler/metrics/custom_stat.proto

package metrics

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CustomStatValue struct {
	StatName             string   `protobuf:"bytes,1,opt,name=stat_name,json=statName,proto3" json:"stat_name,omitempty"`
	StatValue            float64  `protobuf:"fixed64,2,opt,name=stat_value,json=statValue,proto3" json:"stat_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomStatValue) Reset()         { *m = CustomStatValue{} }
func (m *CustomStatValue) String() string { return proto.CompactTextString(m) }
func (*CustomStatValue) ProtoMessage()    {}
func (*CustomStatValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_e23bcf0a4a600aa5, []int{0}
}

func (m *CustomStatValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomStatValue.Unmarshal(m, b)
}
func (m *CustomStatValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomStatValue.Marshal(b, m, deterministic)
}
func (m *CustomStatValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomStatValue.Merge(m, src)
}
func (m *CustomStatValue) XXX_Size() int {
	return xxx_messageInfo_CustomStatValue.Size(m)
}
func (m *CustomStatValue) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomStatValue.DiscardUnknown(m)
}

var xxx_messageInfo_CustomStatValue proto.InternalMessageInfo

func (m *CustomStatValue) GetStatName() string {
	if m != nil {
		return m.StatName
	}
	return ""
}

func (m *CustomStatValue) GetStatValue() float64 {
	if m != nil {
		return m.StatValue
	}
	return 0
}

type CustomStat struct {
	PodName   string `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Timestamp int64  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Process uptime in seconds.
	ProcessUptime        float64            `protobuf:"fixed64,3,opt,name=process_uptime,json=processUptime,proto3" json:"process_uptime,omitempty"`
	Values               []*CustomStatValue `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CustomStat) Reset()         { *m = CustomStat{} }
func (m *CustomStat) String() string { return proto.CompactTextString(m) }
func (*CustomStat) ProtoMessage()    {}
func (*CustomStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_e23bcf0a4a600aa5, []int{1}
}

func (m *CustomStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomStat.Unmarshal(m, b)
}
func (m *CustomStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomStat.Marshal(b, m, deterministic)
}
func (m *CustomStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomStat.Merge(m, src)
}
func (m *CustomStat) XXX_Size() int {
	return xxx_messageInfo_CustomStat.Size(m)
}
func (m *CustomStat) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomStat.DiscardUnknown(m)
}

var xxx_messageInfo_CustomStat proto.InternalMessageInfo

func (m *CustomStat) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *CustomStat) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *CustomStat) GetProcessUptime() float64 {
	if m != nil {
		return m.ProcessUptime
	}
	return 0
}

func (m *CustomStat) GetValues() []*CustomStatValue {
	if m != nil {
		return m.Values
	}
	return nil
}

type CustomWireMessage struct {
	Namespace            string      `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Stat                 *CustomStat `protobuf:"bytes,3,opt,name=stat,proto3" json:"stat,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CustomWireMessage) Reset()         { *m = CustomWireMessage{} }
func (m *CustomWireMessage) String() string { return proto.CompactTextString(m) }
func (*CustomWireMessage) ProtoMessage()    {}
func (*CustomWireMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_e23bcf0a4a600aa5, []int{2}
}

func (m *CustomWireMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomWireMessage.Unmarshal(m, b)
}
func (m *CustomWireMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomWireMessage.Marshal(b, m, deterministic)
}
func (m *CustomWireMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomWireMessage.Merge(m, src)
}
func (m *CustomWireMessage) XXX_Size() int {
	return xxx_messageInfo_CustomWireMessage.Size(m)
}
func (m *CustomWireMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomWireMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CustomWireMessage proto.InternalMessageInfo

func (m *CustomWireMessage) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *CustomWireMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CustomWireMessage) GetStat() *CustomStat {
	if m != nil {
		return m.Stat
	}
	return nil
}

type CustomWireMessages struct {
	Messages             []*CustomWireMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CustomWireMessages) Reset()         { *m = CustomWireMessages{} }
func (m *CustomWireMessages) String() string { return proto.CompactTextString(m) }
func (*CustomWireMessages) ProtoMessage()    {}
func (*CustomWireMessages) Descriptor() ([]byte, []int) {
	return fileDescriptor_e23bcf0a4a600aa5, []int{3}
}

func (m *CustomWireMessages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomWireMessages.Unmarshal(m, b)
}
func (m *CustomWireMessages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomWireMessages.Marshal(b, m, deterministic)
}
func (m *CustomWireMessages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomWireMessages.Merge(m, src)
}
func (m *CustomWireMessages) XXX_Size() int {
	return xxx_messageInfo_CustomWireMessages.Size(m)
}
func (m *CustomWireMessages) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomWireMessages.DiscardUnknown(m)
}

var xxx_messageInfo_CustomWireMessages proto.InternalMessageInfo

func (m *CustomWireMessages) GetMessages() []*CustomWireMessage {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
	proto.RegisterType((*CustomStatValue)(nil), "metrics.CustomStatValue")
	proto.RegisterType((*CustomStat)(nil), "metrics.CustomStat")
	proto.RegisterType((*CustomWireMessage)(nil), "metrics.CustomWireMessage")
	proto.RegisterType((*CustomWireMessages)(nil), "metrics.CustomWireMessages")
}

func init() {
	proto.RegisterFile("pkg/autoscaler/metrics/custom_stat.proto", fileDescriptor_e23bcf0a4a600aa5)
}

var fileDescriptor_e23bcf0a4a600aa5 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x5f, 0x4b, 0xc3, 0x30,
	0x14, 0xc5, 0xc9, 0x5a, 0xb6, 0xf6, 0x0e, 0x15, 0xe3, 0x4b, 0xfc, 0x07, 0xa5, 0x20, 0xf6, 0xa9,
	0x95, 0x09, 0x7e, 0x01, 0x5f, 0x9d, 0x0f, 0x11, 0xf5, 0xb1, 0xc4, 0x2e, 0x8c, 0xe2, 0xb2, 0x84,
	0xde, 0xd4, 0x8f, 0xe3, 0x67, 0x95, 0x5c, 0xab, 0x1d, 0xd3, 0xb7, 0x70, 0xce, 0xaf, 0xe7, 0x9e,
	0x43, 0xa1, 0x70, 0xef, 0xeb, 0x4a, 0xf5, 0xde, 0x62, 0xa3, 0x36, 0xba, 0xab, 0x8c, 0xf6, 0x5d,
	0xdb, 0x60, 0xd5, 0xf4, 0xe8, 0xad, 0xa9, 0xd1, 0x2b, 0x5f, 0xba, 0xce, 0x7a, 0xcb, 0x67, 0x83,
	0x95, 0x2f, 0xe1, 0xe8, 0x9e, 0xdc, 0x27, 0xaf, 0xfc, 0x8b, 0xda, 0xf4, 0x9a, 0x9f, 0x43, 0x1a,
	0xc8, 0x7a, 0xab, 0x8c, 0x16, 0x2c, 0x63, 0x45, 0x2a, 0x93, 0x20, 0x3c, 0x2a, 0xa3, 0xf9, 0x25,
	0x00, 0x99, 0x1f, 0x01, 0x15, 0x93, 0x8c, 0x15, 0x4c, 0x12, 0x4e, 0xdf, 0xe6, 0x9f, 0x0c, 0x60,
	0xcc, 0xe3, 0xa7, 0x90, 0x38, 0xbb, 0xda, 0x4d, 0x9a, 0x39, 0xbb, 0xa2, 0xa0, 0x0b, 0x48, 0x7d,
	0x6b, 0x34, 0x7a, 0x65, 0x1c, 0xe5, 0x44, 0x72, 0x14, 0xf8, 0x15, 0x1c, 0xba, 0xce, 0x36, 0x1a,
	0xb1, 0xee, 0x5d, 0x90, 0x45, 0x44, 0xa7, 0x0e, 0x06, 0xf5, 0x99, 0x44, 0x7e, 0x03, 0x53, 0x2a,
	0x82, 0x22, 0xce, 0xa2, 0x62, 0xbe, 0x10, 0xe5, 0xb0, 0xab, 0xdc, 0x1b, 0x25, 0x07, 0x2e, 0xdf,
	0xc2, 0xf1, 0xb7, 0xf5, 0xda, 0x76, 0x7a, 0xa9, 0x11, 0xd5, 0x9a, 0xba, 0x84, 0x8a, 0xe8, 0x54,
	0xf3, 0xd3, 0x73, 0x14, 0x38, 0x87, 0x98, 0x06, 0x4c, 0xc8, 0xa0, 0x37, 0xbf, 0x86, 0x38, 0x8c,
	0xa6, 0x56, 0xf3, 0xc5, 0xc9, 0x3f, 0x67, 0x25, 0x01, 0xf9, 0x03, 0xf0, 0x3f, 0xf7, 0x90, 0xdf,
	0x41, 0x62, 0x86, 0xb7, 0x60, 0xd4, 0xfc, 0x6c, 0x2f, 0x62, 0x07, 0x97, 0xbf, 0xec, 0xdb, 0x94,
	0xfe, 0xde, 0xed, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x6e, 0x7f, 0xc1, 0xe9, 0x01, 0x00,
	0x00,
}
